#!/usr/bin/env python

import RPi.GPIO as GPIO
import SimpleMFRC522

reader = SimpleMFRC522.SimpleMFRC522()

try:
	text = raw_input('Customer name: ')
	print('Tap the tag to write')
	reader.write(text)
	print('Written successfully')

finally:
	GPIO.cleanup()

